name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-and-lint:
    name: 🔧 Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint (biome)
        run: pnpm biome ci --no-errors-on-unmatched --error-on-warnings

      - name: Run Tests
        run: pnpm test

      - name: Build docs
        run: pnpm --filter ./docs build
